### ISSUE TITLE
Can you write a detailed steps about this project？

### ISSUE THREAD

**Issue by lamb-wolf1** [sh1newu/SepMark#3]
I'm sorry, I'm a beginner. I would love to replicate this code, but I don't know every step of running this program. I would appreciate it if you could write a more detailed procedure!

**Comment by sh1newu** [comment]
I plan to release the codes and pre-trained models about the Deepfake algorithms used in our experiments, so that everyone may reproduce them effortlessly. This will probably be scheduled after these busy days. Please kindly wait for the update.

**Comment by lamb-wolf1** [comment]
> I plan to release the codes and pre-trained models about the Deepfake algorithms used in our experiments, so that everyone may reproduce them effortlessly. This will probably be scheduled after these busy days. Please kindly wait for the update.

It's a great job and I'm looking forward to it

**Comment by sh1newu** [comment]
See the README file, please.
